import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import SideNavBar from "../components/SideNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          'min-h-screen w-full bg-white slate-900 text-slate-900 flex',
          inter.className,
          {
            'debug-screens': process.env.NODE_ENV==='development'
          }
        )}
      >
        {/* Боковая панель */}
        {/* <p className="border">Боковая панель</p> */}
        <SideNavBar />

        {/* Основное содержимое страницы */}

        <div className="w-full p-8">
          {children}
        </div>
      </body>
    </html>
  );
}